### ISSUE TITLE
cocalc-docker: discontinued

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#61]
the page https://doc.cocalc.com/docker-image.html should shrink down to an explanation, that this is a discontinued product.

**Comment by novoselt** [comment]
I got very confused tracking it down since I could not locate the source file. That's because it is gone, but that trick with gh-pages as "a special independent branch" keeps copies of old deleted files. In particular the navigation panel is different at the link above, because it was generated a while ago.

So what is the proper solution here? Should I recreate the file, put a deprecated note there, and never ever delete a page, but just take it out of TOC and put a message that it is gone? Can we customize 404 to have a link to the main page instead? Or just redirect there automatically?

**Comment by haraldschilly** [comment]
hmm, maybe we should delete all files and re-deploy, such that there aren't any old ones lying around? I don't remember how I got to that link. In any case, I'll delete that page, just to avoid future confusion.

**Comment by haraldschilly** [comment]
I've just deleted two old pages, manually. Probably best would be to delete all files prior to copying the artifacts over and deploying it. 

https://github.com/sagemathinc/cocalc-doc/commit/c62c6ab8cb759a7fdc528b6aca18a3437c46e564

**Comment by novoselt** [comment]
I'm following deployment instructions that Hal has passed to me - when I tried to be more clever with rsync and delete no longer existing files, things got really messed up!
