### ISSUE TITLE
cocalc cloud → onprem

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#62]
Rename all "CoCalc Cloud" → "CoCalc OnPrem" and related phrases.

In particular, this concerns https://doc.cocalc.com/cocalc-cloud.html 

Regarding the URL itself, I propose to move this page to cocalc-onprem.html and keep the cocalc-cloud.html URL: the old page should just mention that it has been renamed and link to the new page (to avoid broken links)

Also, all hosts in URLs have to change: `doc-cloud.cocalc.com` → `onprem.cocalc.com`

**Comment by novoselt** [comment]
This is very redundant:
![image](https://github.com/sagemathinc/cocalc-doc/assets/1993227/56525097-d8a2-4d67-a0bf-fee839592874)
There has to be just one page mentioning CoCalc OnPrem as well as On Prem Compute Servers and link to much more detailed real docs.

**Comment by williamstein** [comment]
Also "On-Premises" versus "On Prem" versus "OnPrem".  Which is it?  We should make a consistent choice everywhere.  I personally think "OnPrem" is what we should switch to everywhere.

**Comment by williamstein** [comment]
> Although if one can actually install "CoCalc OnPrem" on an "OnPrem" Compute Server, things may get confusing ;-)

One can! 

I just made a change in the frontend UI: https://github.com/sagemathinc/cocalc/commit/accd6d27f6087331b44a76cda336aae57bea6b04

**Comment by novoselt** [comment]
After pondering what to do with links to old blog posts and discussions and how to rephrase things in general, I've deleted most of the content linking to full CoCalc OnPrem instead and mentioning the store page as well. I've kept OnPrem Compute Server section since for some people that may be exactly what they need. The main page file name is still on-premises, should we change it? Internal links are done using ref instead of doc now, so TOC is the only place that relies on the file name.

https://doc.cocalc.com/cocalc-cloud.html

https://doc.cocalc.com/on-premises.html
