### ISSUE TITLE
factor out aspell config to dedicated howto page

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#8]
see https://github.com/sagemathinc/cocalc-doc/pull/7

**Comment by DrXyzzy** [comment]
- "aspell" instructions factored out to the frame editor page: https://doc.cocalc.com/latex-faq.html#spell-check-a-latex-document
- Added: a spellcheck section to the frame editor page: https://doc.cocalc.com/frame-editor.html#spell-checker
- "aspell" seems to support only tex, html, nroff, and email formats, looking at the Linux man page
- Since 2020-06-01 codemirror has supported the browser's native spellcheck. See #3461.
- As of Google Chrome "Version 99.0.4844.83 (Official Build) (x86_64)", the "Customize spell check" options are unavailable for viewing and editing the spell check dictionary. I don't know if this is a temporary bug or a permanently removed feature.
